apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-grxv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-grxv
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-grxv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-grxv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-grxv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zzuk-tenant/status-quarkus-io/statusquarkusio-grxv@sha256:b1e597336da881ae16106f6cf7d89109020269dc0e89c4880febe5948e6e808e
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
